deploy snapshot - Fail if current version is not a snapshot

diff --git a/.github/workflows/deploy-snapshot.yml b/.github/workflows/deploy-snapshot.yml
--- a/.github/workflows/deploy-snapshot.yml
+++ b/.github/workflows/deploy-snapshot.yml
@@ -23,6 +23,15 @@ jobs:
         id: checkSnapshot
         uses: ./.github/actions/check-if-snapshot
 
+      - name: Fail if current version is not a snapshot
+        if: ${{ steps.checkSnapshot.outputs.is_snapshot == 'false' }}
+        run: |
+          echo "Error: The current version is not a snapshot, which is weird, because it should happen automatically.\
+          Either workflow for releasing new version failed - in that case, please re-run it (should be idempotent so no worries re-running it).\
+          Or there happened some collision between running release and this workflow. In that case, re-running this workflow \
+          should help. If nothing helps, it would be very nice of you if you could fix the problem if you can and send PR."
+          exit 1
+
       - name: Publish snapshot to Sonatype
         if: ${{ steps.checkSnapshot.outputs.is_snapshot == 'true' }}
         uses: ./.github/actions/deploy-sonatype
